# Site settings
title: OnyxRaven Blog
email: onyx@onyxraven.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, tips and code from a ruby developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onyxraven.com" # the base hostname & protocol for your site
twitter_username: onyxraven
github_username:  onyxraven
timezone: America/Denver


# Build settings
markdown: kramdown
highlighter: pygments
github: onyxraven

kramdown:
  input: GFM
