# Site settings
title: OnyxRaven
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, tips, and code from a software engineer
twitter_username: onyxraven
github_username:  onyxraven
timezone: America/Los_Angeles

# Build settings
plugins:
- jekyll-coffeescript
- jekyll-gist
- jekyll-github-metadata
- jekyll-paginate
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-avatar
- jemoji
- jekyll-mentions
- jekyll-include-cache

theme: jekyll-theme-hacker
